plugins {
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
}

apply plugin: 'com.gradleup.shadow'

apply from: "https://raw.githubusercontent.com/henkelmax/mod-gradle-scripts/${mod_gradle_script_version}/mod.gradle"

processResources {
    filesMatching('**/*.toml') {
        expand 'mod_version': mod_version,
                'api_version': project(':api').version,
                'neoforge_dependency': neoforge_dependency,
                'minecraft_version': minecraft_version,
                'cloth_config_version': cloth_config_version
    }
}

repositories {
    maven { url = 'https://maven.shedaniel.me/' }
}

dependencies {
    implementation "org.jetbrains:annotations:${jetbrains_annotations_version}"

    //implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"

    minecraftLibrary "io.github.jaredmdobson:concentus:${concentus_version}"
    shadow "io.github.jaredmdobson:concentus:${concentus_version}"

    minecraftLibrary "de.maxhenkel.opus4j:opus4j:${opus4j_version}"
    shadow "de.maxhenkel.opus4j:opus4j:${opus4j_version}"

    minecraftLibrary "de.maxhenkel.rnnoise4j:rnnoise4j:${rnnoise4j_version}"
    shadow "de.maxhenkel.rnnoise4j:rnnoise4j:${rnnoise4j_version}"

    minecraftLibrary "de.maxhenkel.lame4j:lame4j:${lame4j_version}"
    shadow "de.maxhenkel.lame4j:lame4j:${lame4j_version}"

    minecraftLibrary "de.maxhenkel.speex4j:speex4j:${speex4j_version}"
    shadow "de.maxhenkel.speex4j:speex4j:${speex4j_version}"
}

tasks.register('generateJava', Copy) {
    from project(':common').file('src/template/java')
    into "${layout.buildDirectory.asFile.get()}/generated/java"
    expand 'compatibility_version': voicechat_compatibility_version,
            'mod_compatible_version': mod_compatible_version,
            'minecraft_version': minecraft_version
}
sourceSets.main.java {
    srcDir "${layout.buildDirectory.asFile.get()}/generated/java"
}
compileJava.dependsOn generateJava

shadowJar {
    relocate 'io.github.jaredmdobson.concentus', 'de.maxhenkel.voicechat.concentus'
    exclude 'natives/*-x86/*'
}
